const allsongs = [
  // Taylor Swift
  { song: "Tim McGraw", album: "Taylor Swift" },
  { song: "Picture to Burn", album: "Taylor Swift" },
  { song: "Teardrops on My Guitar", album: "Taylor Swift" },
  { song: "A Place in This World", album: "Taylor Swift" },
  { song: "Cold as You", album: "Taylor Swift" },
  { song: "The Outside", album: "Taylor Swift" },
  { song: "Tied Together with a Smile", album: "Taylor Swift" },
  { song: "Stay Beautiful", album: "Taylor Swift" },
  { song: "Should've Said No", album: "Taylor Swift" },
  { song: "Mary's Song (Oh My My My)", album: "Taylor Swift" },
  { song: "Our Song", album: "Taylor Swift" },
  { song: "I'm Only Me When I'm with You", album: "Taylor Swift" },
  { song: "Invisible", album: "Taylor Swift" },
  { song: "A Perfectly Good Heart", album: "Taylor Swift" },
  // Fearless
  { song: "Jump Then Fall", album: "Fearless" },
  { song: "Untouchable", album: "Fearless" },
  { song: "Forever & Always", album: "Fearless" },
  { song: "Come In With The Rain", album: "Fearless" },
  { song: "SuperStar", album: "Fearless" },
  { song: "The Other Side Of The Door", album: "Fearless" },
  { song: "Fearless", album: "Fearless" },
  { song: "Fifteen", album: "Fearless" },
  { song: "Love Story", album: "Fearless" },
  { song: "Hey Stephen", album: "Fearless" },
  { song: "White Horse", album: "Fearless" },
  { song: "You Belong With Me", album: "Fearless" },
  { song: "Breathe", album: "Fearless" },
  { song: "Tell Me Why", album: "Fearless" },
  { song: "You're Not Sorry", album: "Fearless" },
  { song: "The Way I Loved You", album: "Fearless" },
  { song: "The Best Day", album: "Fearless" },
  { song: "Change", album: "Fearless" },
  // Speak Now
  { song: "Mine", album: "Speak Now" },
  { song: "Sparks Fly", album: "Speak Now" },
  { song: "Back to December", album: "Speak Now" },
  { song: "Speak Now", album: "Speak Now" },
  { song: "Dear John", album: "Speak Now" },
  { song: "Mean", album: "Speak Now" },
  { song: "The Story of Us", album: "Speak Now" },
  { song: "Never Grow Up", album: "Speak Now" },
  { song: "Enchanted", album: "Speak Now" },
  { song: "Better Than Revenge", album: "Speak Now" },
  { song: "Innocent", album: "Speak Now" },
  { song: "Haunted", album: "Speak Now" },
  { song: "Last Kiss", album: "Speak Now" },
  { song: "Long Live", album: "Speak Now" },
  { song: "Ours", album: "Speak Now" },
  { song: "If This Was A Movie", album: "Speak Now" },
  { song: "Superman", album: "Speak Now" },
  // Red
  { song: "State of Grace", album: "Red" },
  { song: "Red", album: "Red" },
  { song: "Treacherous", album: "Red" },
  { song: "I Knew You Were Trouble", album: "Red" },
  { song: "All Too Well", album: "Red" },
  { song: "22", album: "Red" },
  { song: "We Are Never Ever Getting Back Together", album: "Red" },
  { song: "Begin Again", album: "Red" },

];

export default allsongs;
