const allsongs = [
  // Debut
  { song: "Tim McGraw", album: "Taylor Swift" },
  { song: "Picture to Burn", album: "Taylor Swift" },
  { song: "Teardrops on My Guitar", album: "Taylor Swift" },
  { song: "A Place in This World", album: "Taylor Swift" },
  { song: "Cold as You", album: "Taylor Swift" },
  { song: "The Outside", album: "Taylor Swift" },
  { song: "Tied Together with a Smile", album: "Taylor Swift" },
  { song: "Stay Beautiful", album: "Taylor Swift" },
  { song: "Should've Said No", album: "Taylor Swift" },
  { song: "Mary's Song (Oh My My My)", album: "Taylor Swift" },
  { song: "Our Song", album: "Taylor Swift" },
  { song: "I'm Only Me When I'm with You", album: "Taylor Swift" },
  { song: "Invisible", album: "Taylor Swift" },
  { song: "A Perfectly Good Heart", album: "Taylor Swift" },
  // Fearless
  { song: "Jump Then Fall", album: "Fearless" },
  { song: "Untouchable", album: "Fearless" },
  { song: "Forever & Always", album: "Fearless" },
  { song: "Come In With The Rain", album: "Fearless" },
  { song: "SuperStar", album: "Fearless" },
  { song: "The Other Side Of The Door", album: "Fearless" },
  { song: "Fearless", album: "Fearless" },
  { song: "Fifteen", album: "Fearless" },
  { song: "Love Story", album: "Fearless" },
  { song: "Hey Stephen", album: "Fearless" },
  { song: "White Horse", album: "Fearless" },
  { song: "You Belong With Me", album: "Fearless" },
  { song: "Breathe", album: "Fearless" },
  { song: "Tell Me Why", album: "Fearless" },
  { song: "You're Not Sorry", album: "Fearless" },
  { song: "The Way I Loved You", album: "Fearless" },
  { song: "The Best Day", album: "Fearless" },
  { song: "Change", album: "Fearless" },
  // Speak Now
  { song: "Mine", album: "Speak Now" },
  { song: "Sparks Fly", album: "Speak Now" },
  { song: "Back to December", album: "Speak Now" },
  { song: "Speak Now", album: "Speak Now" },
  { song: "Dear John", album: "Speak Now" },
  { song: "Mean", album: "Speak Now" },
  { song: "The Story of Us", album: "Speak Now" },
  { song: "Never Grow Up", album: "Speak Now" },
  { song: "Enchanted", album: "Speak Now" },
  { song: "Better Than Revenge", album: "Speak Now" },
  { song: "Innocent", album: "Speak Now" },
  { song: "Haunted", album: "Speak Now" },
  { song: "Last Kiss", album: "Speak Now" },
  { song: "Long Live", album: "Speak Now" },
  { song: "Ours", album: "Speak Now" },
  { song: "If This Was A Movie", album: "Speak Now" },
  { song: "Superman", album: "Speak Now" },
  // Red
  { song: "State of Grace", album: "Red" },
  { song: "Red", album: "Red" },
  { song: "Treacherous", album: "Red" },
  { song: "I Knew You Were Trouble", album: "Red" },
  { song: "All Too Well", album: "Red" },
  { song: "22", album: "Red" },
  { song: "I Almost Do", album: "Red" },
  { song: "We Are Never Ever Getting Back Together", album: "Red" },
  { song: "Stay Stay Stay", album: "Red" },
  { song: "The Last Time", album: "Red" },
  { song: "Holy Ground", album: "Red" },
  { song: "Sad Beautiful Tragic", album: "Red" },
  { song: "The Lucky One", album: "Red" },
  { song: "Everything Has Changed", album: "Red" },
  { song: "Starlight", album: "Red" },
  { song: "Begin Again", album: "Red" },
  { song: "The Moment I Knew", album: "Red" },
  { song: "Come Back...Be Here", album: "Red" },
  { song: "Girl At Home", album: "Red" },
  // 1989
  { song: "Welcome To New York", album: "1989" },
  { song: "Blank Space", album: "1989" },
  { song: "Style", album: "1989" },
  { song: "Out Of The Woods", album: "1989" },
  { song: "All You Had To Do Was Stay", album: "1989" },
  { song: "Shake It Off", album: "1989" },
  { song: "I Wish You Would", album: "1989" },
  { song: "Bad Blood", album: "1989" },
  { song: "Wildest Dreams", album: "1989" },
  { song: "How You Get The Girl", album: "1989" },
  { song: "This Love", album: "1989" },
  { song: "I Know Places", album: "1989" },
  { song: "Clean", album: "1989" },
  { song: "Wonderland", album: "1989" },
  { song: "You Are In Love", album: "1989" },
  { song: "New Romantics", album: "1989" },
  // reputation
  { song: "...Ready For It?", album: "reputation" },
  { song: "End Game", album: "reputation" },
  { song: "I Did Something Bad", album: "reputation" },
  { song: "Don't Blame Me", album: "reputation" },
  { song: "Delicate", album: "reputation" },
  { song: "Look What You Made Me Do", album: "reputation" },
  { song: "So It Goes...", album: "reputation" },
  { song: "Gorgeous", album: "reputation" },
  { song: "Getaway Car", album: "reputation" },
  { song: "King Of My Heart", album: "reputation" },
  { song: "Dancing With Our Hands Tied", album: "reputation" },
  { song: "Dress", album: "reputation" },
  { song: "This Is Why We Can't Have Nice Things", album: "reputation" },
  { song: "Call It What You Want", album: "reputation" },
  { song: "New Year's Day", album: "reputation" },
  // Lover
  { song: "I Forgot That You Existed", album: "Lover" },
  { song: "Cruel Summer", album: "Lover" },
  { song: "Lover", album: "Lover" },
  { song: "The Man", album: "Lover" },
  { song: "The Archer", album: "Lover" },
  { song: "I Think He Knows", album: "Lover" },
  { song: "Miss Americana & The Heartbreak Prince", album: "Lover" },
  { song: "Paper Rings", album: "Lover" },
  { song: "Cornelia Street", album: "Lover" },
  { song: "Death By A Thousand Cuts", album: "Lover" },
  { song: "London Boy", album: "Lover" },
  { song: "Soon You'll Get Better", album: "Lover" },
  { song: "False God", album: "Lover" },
  { song: "You Need To Calm Down", album: "Lover" },
  { song: "Afterglow", album: "Lover" },
  { song: "ME!", album: "Lover" },
  { song: "It's Nice To Have A Friend", album: "Lover" },
  { song: "Daylight", album: "Lover" },
  // folklore
  { song: "the 1", album: "folklore" },
  { song: "cardigan", album: "folklore" },
  { song: "the last great american dynasty", album: "folklore" },
  { song: "exile", album: "folklore" },
  { song: "my tears ricochet", album: "folklore" },
  { song: "mirrorball", album: "folklore" },
  { song: "seven", album: "folklore" },
  { song: "august", album: "folklore" },
  { song: "this is me trying", album: "folklore" },
  { song: "illicit affairs", album: "folklore" },
  { song: "invisible string", album: "folklore" },
  { song: "mad woman", album: "folklore" },
  { song: "epiphany", album: "folklore" },
  { song: "betty", album: "folklore" },
  { song: "peace", album: "folklore" },
  { song: "hoax", album: "folklore" },
  // evermore
  { song: "willow", album: "evermore" },
  { song: "champagne problems", album: "evermore" },
  { song: "gold rush", album: "evermore" },
  { song: "'tis the damn season", album: "evermore" },
  { song: "tolerate it", album: "evermore" },
  { song: "no body, no crime", album: "evermore" },
  { song: "happiness", album: "evermore" },
  { song: "dorothea", album: "evermore" },
  { song: "coney island", album: "evermore" },
  { song: "ivy", album: "evermore" },
  { song: "cowboy like me", album: "evermore" },
  { song: "long story short", album: "evermore" },
  { song: "marjorie", album: "evermore" },
  { song: "closure", album: "evermore" },
  { song: "evermore", album: "evermore" },
  // Midnights
  { song: "Lavender Haze", album: "Midnights" },
  { song: "Maroon", album: "Midnights" },
  { song: "Anti-Hero", album: "Midnights" },
  { song: "Snow On The Beach", album: "Midnights" },
  { song: "You're On Your Own Kid", album: "Midnights" },
  { song: "Midnight Rain", album: "Midnights" },
  { song: "Question...?", album: "Midnights" },
  { song: "Vigilante Shit", album: "Midnights" },
  { song: "Bejeweled", album: "Midnights" },
  { song: "Labyrinth", album: "Midnights" },
  { song: "Karma", album: "Midnights" },
  { song: "Sweet Nothing", album: "Midnights" },
  { song: "Mastermind", album: "Midnights" },
  { song: "The Great War", album: "Midnights" },
  { song: "Bigger Than The Whole Sky", album: "Midnights" },
  { song: "Paris", album: "Midnights" },
  { song: "High Infidelity", album: "Midnights" },
  { song: "Glitch", album: "Midnights" },
  { song: "Would've, Could've, Should've", album: "Midnights" },
  { song: "Dear Reader", album: "Midnights" },
  // THE TORTURED POETS DEPARTMENT
  { song: "Fortnight", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "The Tortured Poets Department", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "My Boy Only Breaks His Favorite Toys", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "Down Bad", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "So Long, London", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "But Daddy I Love Him", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "Fresh Out The Slammer", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "Florida!!!", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "Guility as Sin?", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "Who's Afraid of Little Old Me?", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "I Can Fix Him (No Really I Can)", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "loml", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "I Can Do It With A Broken Heart", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "The Smallest Man That Ever Lived", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "The Alchmey", album: "THE TORTURED POETS DEPARTMENT" },
  { song: "Clara Bow", album: "THE TORTURED POETS DEPARTMENT" },
  // The Life of a Showgirl
  { song: "The Fate of Ophelia", album: "The Life of a Showgirl" },
  { song: "Elizabeth Taylor", album: "The Life of a Showgirl" },
  { song: "Opalite", album: "The Life of a Showgirl" },
  { song: "Father Figure", album: "The Life of a Showgirl" },
  { song: "Eldest Daughter", album: "The Life of a Showgirl" },
  { song: "Ruin the Friendship", album: "The Life of a Showgirl" },
  { song: "Actually Romantic", album: "The Life of a Showgirl" },
  { song: "Wi$h Li$t", album: "The Life of a Showgirl" },
  { song: "Wood", album: "The Life of a Showgirl" },
  { song: "CANCELLED!", album: "The Life of a Showgirl" },
  { song: "Honey", album: "The Life of a Showgirl" },
  { song: "The Life of a Showgirl", album: "The Life of a Showgirl" },
];

export default allsongs;
